# Site settings
title: ak 的 free world
email: altair.ke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  分享我的所见所闻
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kirkcoco.github.io" # the base hostname & protocol for your site
twitter_username: ak5t
github_username:  kirkcoco

# Build settings
markdown: kramdown
